# Generated by Django 3.1.2 on 2020-11-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
