# Generated by Django 3.1.2 on 2020-11-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('date_of_admit', models.DateField()),
                ('contact_no', models.CharField(max_length=15)),
                ('blood_grp', models.CharField(max_length=5)),
                ('dept', models.CharField(choices=[('Pediatrician', 'Pediatrician'), ('Gynecologist', 'Gynecologist'), ('Gynecologist', 'Gynecologist'), ('Psychiatrist', 'Psychiatrist'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Nephrologist', 'Nephrologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Otolaryngologist', 'Otolaryngologist'), ('Pulmonologist', 'Pulmonologist'), ('Neurologist', 'Neurologist'), ('Oncologist', 'Oncologist')], max_length=50)),
            ],
        ),
    ]
