# Generated by Django 3.1.2 on 2020-11-15 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='descriptiom',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
