# Generated by Django 3.1.2 on 2020-10-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201031_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('Pediatrician', 'Pediatrician'), ('Gynecologist', 'Gynecologist'), ('Gynecologist', 'Gynecologist'), ('Psychiatrist', 'Psychiatrist'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Nephrologist', 'Nephrologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Otolaryngologist', 'Otolaryngologist'), ('Pulmonologist', 'Pulmonologist'), ('Neurologist', 'Neurologist'), ('Oncologist', 'Oncologist')], max_length=50)),
                ('date_of_join', models.DateField()),
            ],
        ),
    ]
