# Generated by Django 3.1.2 on 2020-10-31 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201031_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='doctors'),
            preserve_default=False,
        ),
    ]
