# Generated by Django 3.1.2 on 2020-10-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201031_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
