# Generated by Django 3.1.2 on 2020-11-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201102_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
